package: pycalphad
engine:
  - python=2.7
  - python=3.3
  - python=3.4
platform:
#  - linux-32
  - linux-64
#  - osx-64
#  - win-32
#  - win-64
script:
    - conda build -c richardotis .
build_targets: conda
