language: python
sudo: false
notifications:
  email: false

matrix:
    include:
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=2.7

# Setup anaconda
before_install:
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
# Install packages
install:
  - pip install coveralls
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pandas sympy pyparsing
  - conda install --yes xray
  - conda install --yes -c richardotis autograd
  - python setup.py install
 
# Run test
script:
  - nosetests --with-coverage
after_success:
  - coveralls
