language: python
sudo: false
notifications:
  email: false
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/miniconda2
before_cache:
  - rm -Rf $HOME/miniconda2/envs

matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
          env: DEPLOY_ENC_LABEL=e64cfe3b4e81
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=2.7
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=3.4
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=3.5

# Setup anaconda
before_install:
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        wget -nc http://repo.continuum.io/miniconda/Miniconda2-3.19.0-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget -nc http://repo.continuum.io/miniconda/Miniconda2-3.19.0-Linux-x86_64.sh -O miniconda.sh;
      fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -f
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  - conda config --add channels conda-forge
# unnecessary since we aren't trying to plot during tests anymore
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
# Install packages
install:
  - pip install coveralls
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose pandas sympy pyparsing dask dill
  - conda install --yes xarray tqdm
  - conda install --yes autograd
  - pip install -e .
 
# Run test
script:
  - nosetests --with-coverage
  - conda install --yes sphinx
  - pip install sphinx_rtd_theme
  - bash ci/deploy.sh
after_success:
  - coveralls
