language: python
sudo: required
dist: trusty
notifications:
  email: false

matrix:
    include:
        - name: "Python 2.7 on Xenial Linux"
          python: 2.7           # this works for Linux but is ignored on macOS or Windows
          dist: xenial
        - name: "Python 3.6 on Xenial Linux"
          python: 3.6           # this works for Linux but is ignored on macOS or Windows
          dist: xenial
          env: DEPLOY_ENC_LABEL=e64cfe3b4e81
        - name: "Python 3.7 on Xenial Linux"
          python: 3.7           # this works for Linux but is ignored on macOS or Windows
          dist: xenial
        - name: "Python 2.7 on macOS"
          language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=2.7
        - name: "Python 3.6 on macOS"
          language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=3.6
        - name: "Python 3.7 on macOS"
          os: osx
          osx_image: xcode10.1
          language: generic       # 'language: python' is an error on Travis CI macOS
          env: TRAVIS_PYTHON_VERSION=3.7

# Setup anaconda
before_install:
  - set -e # Exit immediately if a command exits with a non-zero status
  - ./ci/travis_legacy_deps.sh

# Install packages
install:
  - |
      . $HOME/miniconda2/etc/profile.d/conda.sh
      conda deactivate
      conda activate condaenv
      echo "!!! Installing pycalphad dependencies via conda"
      conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest pytest-cov pandas sympy pyparsing dask dill python-symengine xarray cython cyipopt
      echo "!!! conda installing test packages"
      conda install --yes sphinx sphinx_rtd_theme coveralls ipython
      echo "!!! pip pycalphad as editable"
      pip install -e .

# Run test
script:
  - |
      echo "!!! conda list output"
      conda list
      echo "!!! matplotlib py27 fix"
      echo 'backend : Agg' > matplotlibrc
      echo "!!! running pytest"
      pytest --cov=pycalphad
      echo "!!! Running ci/deploy script"
      bash ci/deploy.sh
      coveralls
