language: python
sudo: required
services:
    - docker
notifications:
  email: false

matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
          env: DEPLOY_ENC_LABEL=e64cfe3b4e81 DOCKER_TAG=linux-python35
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=2.7
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=3.4
        - language: generic
          os: osx
          env: TRAVIS_PYTHON_VERSION=3.5

# Setup anaconda
before_install:
  - |
      if [ -z "$DOCKER_TAG" ]; then
        export DOCKER_USER=richardotis
        docker run --cidfile build.cid -v $(pwd):/pycalphad:rw  -it $DOCKER_USER/pycalphad-base:$DOCKER_TAG /bin/sh -c "cd /pycalphad ; python setup.py install ; python -c 'import pycalphad ; print(pycalphad.__version__)' ; cd /work"
        docker commit `cat build.cid` $DOCKER_USER/pycalphad:$DOCKER_TAG
      else
        ./ci/travis_legacy_deps.sh
        source activate condaenv
      fi
# Install packages
install:
  - |
      if [ -z "$DOCKER_TAG" ]; then
      else
        ./ci/travis_legacy_deps.sh
        source activate condaenv
        pip install coveralls
        conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose pandas sympy pyparsing dask dill
        conda install --yes xarray gcc libgfortran cython
        conda install --yes autograd
        pip install -e .
      fi
 
# Run test
script:
  - |
      if [ -z "$DOCKER_TAG" ]; then
        docker run --rm -v $(pwd):/pycalphad:rw  -it $DOCKER_USER/pycalphad:$DOCKER_TAG /bin/sh -c "nosetests --with-coverage"
      else
        nosetests --with-coverage
      fi
  - conda install --yes sphinx python-coveralls
  - pip install sphinx_rtd_theme
  - bash ci/deploy.sh
after_success:
  - coveralls
