# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tools\appveyor\run_with_env.cmd'

  matrix:

    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-conda64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Make sure the compiler is accessible
  - '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "conda install --yes --quiet conda=4.3.31"
  - "conda config --system --add pinned_packages defaults::conda"
  - "conda -V"
  - "conda create --yes -n condaenv python=%PYTHON_VERSION%"
  - "activate condaenv"
  # workaround for conda-forge/hdf5-feedstock#41
  - "conda install --yes -n condaenv hdf5"
  - "conda config --add channels conda-forge"
  - "conda config --add channels pycalphad"
  # install pycalphad and dependencies
  - "conda install --yes -n condaenv --quiet pip setuptools nose numpy pandas scipy sympy pyparsing matplotlib xarray dask dill 'tinydb>=3.8' cython cyipopt libpython symengine python-symengine"
  - "%CMD_IN_ENV% pip install -e ."

build: false

test_script:
  - "python -c \"import nose ; nose.main()\" -s -v pycalphad"
